### PR TITLE
Fix error during install

### PR DESCRIPTION
**Pull request by Ovvovy**
Pip error during installation.

Can't find `_version.py` and `version.txt` as they are in the `.gitignore`

### CODE REVIEW

**Comment by Julian** [comment]
This change isn't correct -- what version of pip do you have? Can you pastebin the output of the install?

Thanks.

**Comment by Ovvovy** [comment]
http://pastebin.com/Sz1T4hL0

http://pastebin.com/xH09AB04

When I'm not installing from the repository it fail because the version.txt doesn't exist. See pastebin.

**Comment by Julian** [comment]
And where's that from? A check-out or did you in fact download a tarball?

**Comment by Julian** [comment]
Sorry, missed it in your paste in first read, the first one is possibly just a broken release, the second one though isn't a problem, why did you run `rm -r .git` that's what's causing the issue :)?

**Comment by Julian** [comment]
OK, the first paste is a broken sdist, although I'm not sure why you didn't get the wheel, which works -- do you have wheels disabled? I'll fix the sdist now.

**Comment by Ovvovy** [comment]
The rm of .git was to try to find the issue.

Awesome. Thank you.

**Comment by Julian** [comment]
OK sdist is fixed too :), thanks for the report, closing but lemme know if there's anything else you notice.

**Pull request closed without merging**
